services:
  db:
    image: postgres:16-alpine
    container_name: emergy_postgres
    environment:
      POSTGRES_USER: emergy_user
      POSTGRES_PASSWORD: emergy_pass
      POSTGRES_DB: emergy_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
