services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: emergy-tool
      POSTGRES_PASSWORD: emergy-tool
      POSTGRES_DB: emergy_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
