services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./src/.env
    ports:
      - "8000:8000"
    # expose:
    #   - "8000"
    volumes:
      - ./src:/home/python/app
