# Generated by Django 5.2.1 on 2025-05-25 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lci', '0001_initial'),
        ('scale_config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergyCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useful_product', models.FloatField()),
                ('results', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lci.lcimatrix')),
                ('scale_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scale_config.scaleconfig')),
            ],
        ),
    ]
