# Generated by Django 5.2.1 on 2025-05-24 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LCIMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LCICell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=100)),
                ('column', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='lci.lcimatrix')),
            ],
        ),
    ]
